In [1]:
#%tensorflow_version 2.x

In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [3]:
tf.__version__

'2.19.0'

In [4]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [5]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [6]:
y = tf.constant(4.5)
y

<tf.Tensor: shape=(), dtype=float32, numpy=4.5>

In [7]:
z = tf.constant("suneet")
z

<tf.Tensor: shape=(), dtype=string, numpy=b'suneet'>

In [8]:
s = tf.constant([1,2,3,4,5])
s

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [9]:
import numpy as np
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
tf.constant(a)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

2d

In [10]:
tf.constant([[1,2,3], [4,5,6],[7,8,9]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [11]:
tf.constant([1,2,3,4] , shape=(2,2), dtype="int32")

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

3d

In [12]:
tf.constant([[[1,2,3], [4,5,6],[7,8,9]]])

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [13]:
tf.constant([1,2,3,4,5,6] , shape=(1,3,2), dtype="int32")

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)>

# Tensorflow variable

In [14]:
import tensorflow as tf

In [15]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [16]:
x =tf.Variable([1,2,3,4,5])
x

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [17]:
x.name

'Variable:0'

In [18]:
x.shape

TensorShape([5])

In [19]:
x.dtype

tf.int32

In [20]:
y = tf.Variable([1.0, 2, 3.3 , 4])
y

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1. , 2. , 3.3, 4. ], dtype=float32)>

In [21]:
y.name

'Variable:0'

In [22]:
z= tf.Variable( True , False)
z

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [23]:
con = tf.constant([1,2,3,4])
con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [24]:
tf.Variable(con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [25]:
t2d =tf.Variable([[2,3], [4,5]])
t2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [26]:
con = tf.reshape(con, (2,2))

In [27]:
tf.argmax(con)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [28]:
x

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [29]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [30]:
tf.convert_to_tensor(con)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [31]:
x.shape

TensorShape([5])

In [32]:
x

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [33]:
x.assign_add([5,6,7,8,9])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 6,  8, 10, 12, 14], dtype=int32)>

In [34]:
x

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 6,  8, 10, 12, 14], dtype=int32)>

# arthemitic

In [35]:
a= 10
b = 20
a+b

30

In [36]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [37]:
l1 =[1,2,3,4]
l2 =[5,6,7,8]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [38]:
t1 = (2,3,4,5)
t2 = (6,7,8,9)
tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 8, 10, 12, 14], dtype=int32)>

In [39]:
x =tf.constant([1,2,3,4])
y =tf.constant([5,6,7,8])
tf.pow(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([    1,    64,  2187, 65536], dtype=int32)>

In [40]:
x= tf.constant([[2,2] ,[3,3]])
y= tf.constant([[8,16],[2,3]])
tf.subtract(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ -6, -14],
       [  1,   0]], dtype=int32)>

In [41]:
x= tf.constant([[2,2] ,[3,3]])
y= tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [42]:
x = tf.constant([[-2.34 + 4.75] , [-3.25 + 5.75]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.41],
       [2.5 ]], dtype=float32)>

In [43]:
tf.math.multiply(7,6)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [44]:
x = tf.ones([1,2]);
y = tf.ones([2,1]);
x*y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [45]:
x = tf.constant([0.,0.,0.,0.])
y =tf.constant([-2., 0., 2., 5.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [46]:
x = tf.constant([0.,0.,0.,0.])
y =tf.constant([-3.])
tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3., -3., -3., -3.], dtype=float32)>

In [47]:
x= tf.constant([0,0.5,1,5])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

In [48]:
x = tf.constant([16,12,11])
y = tf.constant([4,6,2])
tf.math.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2. , 5.5])>

In [49]:
x= tf.constant([[2,2] ,[3,3]])
y= tf.constant([[8,16],[2,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [50]:
x = tf.constant([[4.0] , [16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [51]:
y = tf.constant([[-4.0] , [16.0]])
tf.sqrt(y)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [52]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [53]:
tf.ones((1)), tf.float32

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [54]:
tf.ones((2,2)),tf.float32 # 2d

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 tf.float32)

In [55]:
tf.ones((2,2,4)),tf.float32 # 3d

(<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=float32)>,
 tf.float32)

In [62]:
t.placeholder(dtype.float32, shape = (400,400))

NameError: name 't' is not defined

In [71]:
tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))

<tf.Tensor 'Placeholder:0' shape=(400, 400) dtype=float32>

In [69]:
tf.compat.v1.disable_eager_execution()

In [72]:
a = tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))
a

<tf.Tensor 'Placeholder_1:0' shape=(400, 400) dtype=float32>

In [73]:
b = tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))
b

<tf.Tensor 'Placeholder_2:0' shape=(400, 400) dtype=float32>

In [76]:
c= tf.add(a,b)
c

<tf.Tensor 'Add_1:0' shape=(400, 400) dtype=float32>

In [77]:
import numpy as np

In [79]:
ones_arry = np.ones((400,400) , np.float32)
ones_arry

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [80]:
with tf.compat.v1.Session() as sess:
  d=sess.run(c, feed_dict={a:ones_arry, b:ones_arry})

In [81]:
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], dtype=float32)